### ISSUE TITLE
BEAUti stalls on loading TreeSetAnalyser

### ISSUE THREAD

**Issue by dmvelasco** [rbouckaert/TreeSetAnalyser#1]
After installing TreeSetAnalyser through BEAUti as per instructions, BEAUti stalls upon restart. BEAUti packaged with BEAST v2.4.5 displays no message while with BEAST v2.4.8 below the loading image displays the message, "Loading package TreeSetAnalyser v0.0.1". I have left it at this stage for several minutes to give it the opportunity to load, should it need extra time due to being a new addition.

macOS v10.13.4 High Sierra, Java 8 Update 171

Any suggestions?

**Comment by dmvelasco** [comment]
Loading from a terminal produces the following information:
```Loading package TreeSetAnalyser v0.0.1
Probing: TreeSetAnalyser.addon.jar Exception in thread "main" java.lang.NoClassDefFoundError: beast/evolution/alignment/AlignmentFromTrait
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at beast.util.AddOnManager.loadPacakge(Unknown Source)
	at beast.util.AddOnManager.loadExternalJars(Unknown Source)
	at beast.app.beauti.Beauti.main2(Unknown Source)
	at beast.app.beauti.Beauti.main(Unknown Source)
	at beast.app.beauti.BeautiLauncher.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: beast.evolution.alignment.AlignmentFromTrait
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

**Comment by dmvelasco** [comment]
I was able to open BEAUti using `java -cp lib/beast.jar beast.app.beauti.Beauti` in a terminal window. Then I uninstalled TreeSetAnalyser and was able to open BEAUti via the program icon. However, this means I am unable to utilize TreeSetAnalyser.

**Comment by rbouckaert** [comment]
Hi Dianne,
Thanks for the bug-report -- it looks like a dependency to the BEAST_CLASSIC and some other packages was not entered in the dependencies. Can you try the following: install BEAST_CLASSIC, NS and Babel then install TreeSetAnalyser again and see whether BEAUti starts?

**Comment by dmvelasco** [comment]
Thanks Remco!

Under BEAST v2.5.0 I installed the dependencies listed above (BEAST_CLASSIC, NS, and Babel), however upon trying to install TreeSetAnalyser I receive the following error:
Install failed because: Package TreeSetAnalyzer requires BEAST versions 2.4.3 to 2.4.9, but no installable version of that package was found.

BEAST versions 2.4.5 and 2.4.8 are installed but NS cannot be installed in v2.4.8 and BEAST_CLASSIC for this version of BEAST is v1.3.2 not v1.4.0, which the error message indicates is required by TreeSetAnalyzer.

**Comment by rbouckaert** [comment]
Sorry for the inconvenience -- I created a new release (v0.0.2) for BEAST v2.5.0 and you should be able to install it from the packagemanager. Hope this fixes all dependency problems.

**Comment by dmvelasco** [comment]
Thank you!

All dependencies and TreeSetAnalyser are now installed and Beauti loads as expected. The next step is to give it a try. Thanks again for fixing the dependencies issue, really appreciate it.

**Comment by rbouckaert** [comment]
Thanks for the confirmation. I'll close the issue.
